# -*- coding: utf-8 -*-
"""FewShotLamma2Makki.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ZOTt1Lu5GxV82fU9MKlyHy0Lfwh2YkV
"""

!pip install transformers

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

# Initialize the model and tokenizer
model_name = "NousResearch/llama-2-7b-chat-hf"  # Replace with the model you have access to
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Initialize the text generation pipeline
text_gen = pipeline('text-generation', model=model, tokenizer=tokenizer)

# Define the doctor's assessment
doctor_assessment = "81F with h/o chronic eosinophilic lung disease, COPD, diastolic CHF, and recent admission for MSSA and pan-sensitive Pseudomonas PNA who presents with fevers, right sided pleuritic chest pain and found to have extensive R sided PE on imaging."

# Make the prompt more explicit
prompt = f"Please summarize the following medical assessment into key terms and conditions: {doctor_assessment}"

# Generate the summary
output = text_gen(prompt, max_length=200, do_sample=True, top_k=50)

# Extract and print the generated summary
generated_text = output[0]['generated_text']
print(f"Generated Summary: {generated_text}\n")

!pip install rouge

from rouge import Rouge

# Initialize rouge object
rouge = Rouge()

# Define the reference and candidate summaries
reference_summary = "Hypoxia:; Hyperkalemia"
candidate_summary = """Here are the key terms and conditions from the medical assessment:
1. Age: 81 years old
2. History of chronic eosinophilic lung disease (CELD) and COPD
3. Diastolic heart failure (CHF)
4. Recent admission for MSSA (methicillin-sensitive Staphylococcus a"""

# Compute ROUGE-L
scores = rouge.get_scores(candidate_summary, reference_summary)
rouge_l = scores[0]['rouge-l']

print(f"ROUGE-L F1 Score: {rouge_l['f']}")
print(f"ROUGE-L Precision: {rouge_l['p']}")
print(f"ROUGE-L Recall: {rouge_l['r']}")